"""Added ffplay_pid to audiopid model

Revision ID: 27e33be91f6b
Revises: 0d983fd8a9ef
Create Date: 2023-02-24 00:02:53.549816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '27e33be91f6b'
down_revision = '0d983fd8a9ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiopid', sa.Column('ffplay_pid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audiopid', 'ffplay_pid')
    # ### end Alembic commands ###
