"""Added Profile model

Revision ID: 353a9996277c
Revises: 27e33be91f6b
Create Date: 2023-02-27 21:19:19.992848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '353a9996277c'
down_revision = '27e33be91f6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stride', sa.Float(), nullable=False),
    sa.Column('mps', sa.Float(), nullable=False),
    sa.Column('ideal_bpm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audiopid', 'ffplay_pid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'audiofile', type_='unique')
    op.drop_table('profile')
    # ### end Alembic commands ###
